import { LoginProvider } from "@/context/loginContext";
import "../styles/global.css";
import type { Metadata } from "next";
import { Marmelad } from "next/font/google";

const marmelad = Marmelad({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="min-h-screen bg-background text-text_color relative z-[1]"
    >
      <body className={marmelad.className}>
        <LoginProvider>{children}</LoginProvider>
      </body>
    </html>
  );
}
